### PR TITLE
Minor fix to BMS watthours to correct scale and unit

### PR DESCRIPTION
**Pull request by FozzieUK**
Just following on from issue #110 this corrects the scale and unit of measurement - a slightly wider decision required as to whether this sensor is needed at all, but at least with these changes it provides a sensor that matches it's name (watthours).

### CODE REVIEW

**Comment by canton7** [comment]
I worry that changing the unit might mess up HA -- I've read issues where the oldest/newest unit is applied to all readings from the sensor, ignoring the unit which was present when the reading was taken.

We also record everything else in kWh. Would it be better to rename the sensor?

**Comment by FozzieUK** [comment]
@canton7 Yes agree on the HA stats, they can be fixed in statistics 'Fix Issue' will allow you to update the previous stats or discard.
But i'm thinking like you that there is no value in this sensor and it just adds to the database - i'd rather it was in a correct format Wh or kWh (it's neither at the moment) or simply removed.

**Comment by canton7** [comment]
>  they can be fixed in statistics 'Fix Issue' will allow you to update the previous stats or discard.

Yeah, but only if people know what's happened! And we'd be expecting every user to do this, which is a bit much.

**Comment by FozzieUK** [comment]
@canton7 Lol, i’d be more surprised if they actually noticed with this sensor ;)

Can I leave it with you and @nathanmarlor to decide if we should rescale to kWh or remove it, i’m happy with either.

**Comment by canton7** [comment]
Yeah I don't mind either. Fixing it and then disabling it is a halfway house at least -- people can get it back if they really want.

**Comment by canton7** [comment]
Also, @nathanmarlor seems to be otherwise occupied at the moment and I don't really want to merge anything in myself, so I suspect there's no rush here. Hopefully he'll be back next week when schools are back.

**Comment by FozzieUK** [comment]
@canton7 yeah, I did think about this, my inclination is to leave the entity ID as it is, it still is a watthours sensor but it reports it's value in kwh (despite previously being the wrong scale). I fixed my install to report watthours only so I could compare it with a self generated wH sensor but it's not a total or total_increasing and resets to zero every few days so i'm not concerned about the history jumping.
Yep no worries there's absolutely no rush at all for this, i've been away myself for a few days and just managed to update to the latest release, I noticed when checking everything that the watthours sensor was wrong so thought i'd better do a PR before I forgot :wink: - hopefully Nathan is having a good break 👍

**Comment by canton7** [comment]
Cool, that's a fair point, makes sense. I'm on board!

**Comment by FozzieUK** [comment]
@canton7 ok, no problem - once #167 has been approved/merged, i'll review and update this to match the new format.

**Comment by canton7** [comment]
Cool, or it might make sense to get this in first as it's smaller, in which case that's a reminder to me to update #167

**Comment by nathanmarlor** [comment]
> Also, @nathanmarlor seems to be otherwise occupied at the moment and I don't really want to merge anything in myself, so I suspect there's no rush here. Hopefully he'll be back next week when schools are back.

I've messaged you on FB 🙂

**Pull request merged**
